import type { DashboardSnapshot } from "@/lib/command-center/types";

const now = new Date();
const iso = (deltaMinutes: number) => new Date(now.getTime() - deltaMinutes * 60_000).toISOString();

export const MOCK_DASHBOARD: DashboardSnapshot = {
  currentUser: "@manu.mishra:anycompany.corp",
  statuses: ["inbox", "assigned", "in_progress", "review", "done", "blocked"],
  priorities: ["low", "medium", "high", "urgent"],
  totals: {
    totalTasks: 11,
    inProgress: 3,
    review: 1,
    completed: 2,
    activeAgents: 2,
  },
  agents: [
    {
      matrixId: "@aaron.phillips:anycompany.corp",
      name: "Aaron Phillips",
      title: "VP Engineering",
      department: "Engineering",
      team: "Platform",
      status: "working",
    },
    {
      matrixId: "@austin.bailey:anycompany.corp",
      name: "Austin Bailey",
      title: "Director Engineering",
      department: "Engineering",
      team: "Product Infra",
      status: "idle",
    },
    {
      matrixId: "@elena.ross:anycompany.corp",
      name: "Elena Ross",
      title: "VP Marketing",
      department: "Marketing",
      team: "Growth",
      status: "working",
    },
    {
      matrixId: "@task.assignments:anycompany.corp",
      name: "Task Assignments Bot",
      title: "Automation",
      department: "Operations",
      team: "Command Center",
      status: "external",
    },
  ],
  tasks: [
    {
      id: "epic_demo_001",
      title: "Q2 Conversion Lift Program",
      description: "Cross-department initiative to improve trial conversion across product and marketing.",
      workItemType: "epic",
      parentTaskId: null,
      department: "Cross-Department",
      departments: ["Engineering", "Marketing", "Product"],
      vp: "Aaron Phillips",
      director: "Austin Bailey",
      manager: "Nina Patel",
      status: "in_progress",
      priority: "high",
      creatorMatrixId: "@manu.mishra:anycompany.corp",
      assigneeMatrixId: "@aaron.phillips:anycompany.corp",
      deliverable: "End-to-end rollout plan with KPI baseline and owners",
      createdAt: iso(300),
      updatedAt: iso(20),
      comments: [],
    },
    {
      id: "feature_demo_001",
      title: "Pricing Explainer Revamp",
      description: "Create clearer pricing sections and ROI proof points.",
      workItemType: "feature",
      parentTaskId: "epic_demo_001",
      department: "Marketing",
      departments: ["Marketing"],
      vp: "Elena Ross",
      director: "Priya Banerjee",
      manager: "Darren King",
      status: "review",
      priority: "medium",
      creatorMatrixId: "@manu.mishra:anycompany.corp",
      assigneeMatrixId: "@elena.ross:anycompany.corp",
      deliverable: "Updated pricing narrative and visual hierarchy spec",
      createdAt: iso(260),
      updatedAt: iso(24),
      comments: [],
    },
    {
      id: "story_demo_001",
      title: "Add testimonial carousel copy",
      description: "Prepare carousel copy with social proof snippets.",
      workItemType: "story",
      parentTaskId: "feature_demo_001",
      department: "Marketing",
      departments: ["Marketing"],
      vp: "Elena Ross",
      director: "Priya Banerjee",
      manager: "Darren King",
      status: "assigned",
      priority: "medium",
      creatorMatrixId: "@elena.ross:anycompany.corp",
      assigneeMatrixId: "@austin.bailey:anycompany.corp",
      deliverable: "Finalized copy deck and review checklist",
      createdAt: iso(220),
      updatedAt: iso(95),
      comments: [],
    },
    {
      id: "task_demo_001",
      title: "Wire task detail modal interactions",
      description: "Move task details from right pane to modal popup.",
      workItemType: "task",
      parentTaskId: "story_demo_001",
      department: "Engineering",
      departments: ["Engineering"],
      vp: "Aaron Phillips",
      director: "Austin Bailey",
      manager: "Nina Patel",
      status: "in_progress",
      priority: "high",
      creatorMatrixId: "@manu.mishra:anycompany.corp",
      assigneeMatrixId: "@aaron.phillips:anycompany.corp",
      deliverable: "Clicking card opens modal with running logs",
      createdAt: iso(210),
      updatedAt: iso(15),
      comments: [
        {
          id: "comment_demo_101",
          authorMatrixId: "@aaron.phillips:anycompany.corp",
          message: "Event delegation updated, validating close interactions now.",
          createdAt: iso(45),
        },
      ],
    },
    {
      id: "feature_demo_002",
      title: "Lane Density Optimization",
      description: "Reduce lane width so six lanes remain in a single row.",
      workItemType: "feature",
      parentTaskId: "epic_demo_001",
      department: "Engineering",
      departments: ["Engineering"],
      vp: "Aaron Phillips",
      director: "Austin Bailey",
      manager: "Nina Patel",
      status: "in_progress",
      priority: "high",
      creatorMatrixId: "@manu.mishra:anycompany.corp",
      assigneeMatrixId: "@austin.bailey:anycompany.corp",
      deliverable: "One-row board lanes with consistent readability",
      createdAt: iso(180),
      updatedAt: iso(22),
      comments: [],
    },
    {
      id: "story_demo_002",
      title: "Create VP/Director/Manager filter system",
      description: "Add hierarchy filters in a dedicated left pane.",
      workItemType: "story",
      parentTaskId: "feature_demo_002",
      department: "Engineering",
      departments: ["Engineering"],
      vp: "Aaron Phillips",
      director: "Austin Bailey",
      manager: "Nina Patel",
      status: "inbox",
      priority: "medium",
      creatorMatrixId: "@manu.mishra:anycompany.corp",
      assigneeMatrixId: null,
      deliverable: "Filter UI with cascading values and reset",
      createdAt: iso(150),
      updatedAt: iso(150),
      comments: [],
    },
    {
      id: "task_demo_002",
      title: "Map hierarchy labels on task cards",
      description: "Display work item type and parent relation hints.",
      workItemType: "task",
      parentTaskId: "story_demo_002",
      department: "Engineering",
      departments: ["Engineering"],
      vp: "Aaron Phillips",
      director: "Austin Bailey",
      manager: "Nina Patel",
      status: "done",
      priority: "low",
      creatorMatrixId: "@manu.mishra:anycompany.corp",
      assigneeMatrixId: "@austin.bailey:anycompany.corp",
      deliverable: "Card metadata strip with type and lineage",
      createdAt: iso(120),
      updatedAt: iso(70),
      comments: [],
    },
    {
      id: "epic_demo_002",
      title: "Sales Enablement Assistant",
      description: "Standalone Sales epic for outbound automation and scripts.",
      workItemType: "epic",
      parentTaskId: null,
      department: "Sales",
      departments: ["Sales"],
      vp: "Ravi Gupta",
      director: "Kelsey Moran",
      manager: "Tim Brooks",
      status: "assigned",
      priority: "medium",
      creatorMatrixId: "@manu.mishra:anycompany.corp",
      assigneeMatrixId: "@aaron.phillips:anycompany.corp",
      deliverable: "Sales automation roadmap and implementation owners",
      createdAt: iso(140),
      updatedAt: iso(90),
      comments: [],
    },
    {
      id: "story_demo_003",
      title: "Cloudflare unblock runbook",
      description: "Design a safe unblock process for agent browser sessions.",
      workItemType: "story",
      parentTaskId: "epic_demo_001",
      department: "Operations",
      departments: ["Operations", "Engineering"],
      vp: "Aaron Phillips",
      director: "Austin Bailey",
      manager: "Nina Patel",
      status: "blocked",
      priority: "urgent",
      creatorMatrixId: "@manu.mishra:anycompany.corp",
      assigneeMatrixId: "@aaron.phillips:anycompany.corp",
      deliverable: "Approved incident-safe access runbook",
      createdAt: iso(80),
      updatedAt: iso(30),
      comments: [
        {
          id: "comment_demo_102",
          authorMatrixId: "@aaron.phillips:anycompany.corp",
          message: "Blocked pending security review sign-off.",
          createdAt: iso(35),
        },
      ],
    },
    {
      id: "task_demo_003",
      title: "Podcast outreach shortlist",
      description: "Compile podcasts and draft outreach templates.",
      workItemType: "task",
      parentTaskId: null,
      department: "Marketing",
      departments: ["Marketing"],
      vp: "Elena Ross",
      director: "Priya Banerjee",
      manager: "Darren King",
      status: "done",
      priority: "low",
      creatorMatrixId: "@manu.mishra:anycompany.corp",
      assigneeMatrixId: "@elena.ross:anycompany.corp",
      deliverable: "Top 20 podcasts and outreach message pack",
      createdAt: iso(90),
      updatedAt: iso(62),
      comments: [],
    },
    {
      id: "feature_demo_003",
      title: "Command center plugin rollout",
      description: "Unify people and tasks through command center APIs.",
      workItemType: "feature",
      parentTaskId: "epic_demo_001",
      department: "Engineering",
      departments: ["Engineering", "Operations"],
      vp: "Aaron Phillips",
      director: "Austin Bailey",
      manager: "Nina Patel",
      status: "inbox",
      priority: "medium",
      creatorMatrixId: "@manu.mishra:anycompany.corp",
      assigneeMatrixId: null,
      deliverable: "Deployment checklist and rollback strategy",
      createdAt: iso(50),
      updatedAt: iso(50),
      comments: [],
    },
  ],
  activity: [
    {
      id: "event_demo_001",
      taskId: "task_demo_001",
      actorMatrixId: "@aaron.phillips:anycompany.corp",
      message: "Status changed: assigned -> in_progress",
      createdAt: iso(40),
    },
    {
      id: "event_demo_002",
      taskId: "feature_demo_002",
      actorMatrixId: "@austin.bailey:anycompany.corp",
      message: "Lane sizing patch applied and under validation",
      createdAt: iso(25),
    },
    {
      id: "event_demo_003",
      taskId: null,
      actorMatrixId: "@task.assignments:anycompany.corp",
      message: "Assignment notification sent to @aaron.phillips:anycompany.corp",
      createdAt: iso(18),
    },
  ],
  source: "mock",
  fetchedAt: now.toISOString(),
};
